# Generated by Django 3.1.3 on 2020-12-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryModels',
            fields=[
                ('part_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('warranty', models.CharField(max_length=10)),
                ('segment', models.CharField(choices=[('PC', 'PC'), ('CV', 'CV'), ('TR', 'TR'), ('OW', 'OHW')], max_length=2)),
                ('nomenclature', models.CharField(max_length=50)),
                ('capacity_C5', models.IntegerField()),
                ('capacity_C20', models.IntegerField()),
                ('reserve_capacity', models.IntegerField()),
                ('CCA', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('BH_type', models.CharField(max_length=10)),
                ('cell_layout', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryRanges',
            fields=[
                ('range_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('range_name', models.CharField(max_length=10)),
                ('technology', models.CharField(max_length=200)),
                ('application', models.CharField(max_length=200)),
                ('service_life', models.IntegerField()),
                ('cold_start_perf', models.IntegerField()),
                ('deep_cylce_resist', models.IntegerField()),
                ('no_of_electrical_consumers', models.IntegerField()),
                ('suitability_of_short_dist', models.IntegerField()),
                ('mainteence', models.CharField(choices=[('MF', 'Maintenance Free'), ('NF', 'Not Maintenance Free')], max_length=2)),
                ('installation_inside_vehicle', models.BooleanField(default=True, null=True)),
                ('installation_angle', models.IntegerField(default=0)),
                ('warranty_duration', models.IntegerField()),
                ('range_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Compatability',
            fields=[
                ('compatability_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('vehicle_class_name', models.CharField(max_length=10)),
                ('OEM', models.CharField(max_length=20)),
                ('vehicle_models', models.CharField(max_length=200)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.batterymodels')),
                ('range_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.batteryranges')),
            ],
        ),
        migrations.AddField(
            model_name='batterymodels',
            name='range_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.batteryranges'),
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('advantage_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('adv1_head', models.CharField(max_length=200, null=True)),
                ('adv1_desc', models.CharField(max_length=200, null=True)),
                ('adv2_head', models.CharField(max_length=200, null=True)),
                ('adv2_desc', models.CharField(max_length=200, null=True)),
                ('adv3_head', models.CharField(max_length=200, null=True)),
                ('adv3_desc', models.CharField(max_length=200, null=True)),
                ('adv4_head', models.CharField(max_length=200, null=True)),
                ('adv4_desc', models.CharField(max_length=200, null=True)),
                ('adv5_head', models.CharField(max_length=200, null=True)),
                ('adv5_desc', models.CharField(max_length=200, null=True)),
                ('adv6_head', models.CharField(max_length=200, null=True)),
                ('adv6_desc', models.CharField(max_length=200, null=True)),
                ('range_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.batteryranges')),
            ],
        ),
    ]
