# Generated by Django 3.1.4 on 2020-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterymodel',
            name='part_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
