# Generated by Django 3.1.3 on 2020-12-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatteryModels',
            new_name='BatteryModel',
        ),
        migrations.RenameModel(
            old_name='BatteryRanges',
            new_name='BatteryRange',
        ),
    ]
