# Generated by Django 3.1.3 on 2020-12-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='range_id',
            new_name='range_name',
        ),
    ]
