# Generated by Django 3.1.3 on 2020-12-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201203_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(default=0, max_length=20)),
                ('bike_pic', models.ImageField(upload_to='')),
                ('range_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.batteryrange')),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compatabilitybike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=20)),
                ('application', models.CharField(max_length=200)),
                ('cs30', models.FloatField()),
                ('battery_type', models.CharField(max_length=20)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bikes')),
            ],
            options={
                'verbose_name': 'Bike Compatability',
                'verbose_name_plural': 'Bike compatabilities',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
