# Generated by Django 3.1.4 on 2020-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_batterymodel_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterymodel',
            name='weight',
            field=models.FloatField(),
        ),
    ]
