# Generated by Django 3.1.3 on 2020-12-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201203_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='range_name',
            new_name='range_id',
        ),
    ]
