# Generated by Django 3.1.3 on 2020-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201202_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batteryrange',
            options={'managed': True, 'verbose_name': 'Battery Range', 'verbose_name_plural': 'Battery Ranges'},
        ),
        migrations.AlterField(
            model_name='batterymodel',
            name='part_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='batteryrange',
            table='',
        ),
    ]
