# Generated by Django 3.1.3 on 2020-12-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bikes_compatabilitybike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amaronseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('battery_type', models.CharField(max_length=50)),
                ('warranty', models.IntegerField()),
                ('usage', models.CharField(max_length=50)),
                ('voltage', models.IntegerField()),
                ('weight', models.FloatField()),
                ('technology', models.CharField(max_length=50)),
                ('variable_ranges', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=550)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Amaron Series',
                'verbose_name_plural': 'Amaron Series',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Amaronmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20)),
                ('item', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('dealer', models.IntegerField()),
                ('price', models.IntegerField()),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.amaronseries')),
            ],
            options={
                'verbose_name': 'Amaron models',
                'verbose_name_plural': 'Amaron models',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Advantagesamaron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv1', models.CharField(blank=True, max_length=200)),
                ('adv2', models.CharField(blank=True, max_length=200)),
                ('adv3', models.CharField(blank=True, max_length=200)),
                ('adv4', models.CharField(blank=True, max_length=200)),
                ('adv5', models.CharField(blank=True, max_length=200)),
                ('adv6', models.CharField(blank=True, max_length=200)),
                ('adv7', models.CharField(blank=True, max_length=200)),
                ('adv8', models.CharField(blank=True, max_length=200)),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.amaronseries')),
            ],
            options={
                'verbose_name': 'Amaron Advantage',
                'verbose_name_plural': 'Amaron Advantages',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
