# Generated by Django 3.1.3 on 2020-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201203_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterymodel',
            name='part_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='batterymodel',
            name='weight',
            field=models.FloatField(),
        ),
    ]
