# Generated by Django 3.1.3 on 2020-12-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201202_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'managed': True, 'verbose_name': 'Advantage', 'verbose_name_plural': 'Advantages'},
        ),
        migrations.AlterModelOptions(
            name='batterymodel',
            options={'managed': True, 'verbose_name': 'Battery Model', 'verbose_name_plural': 'Battery Models'},
        ),
        migrations.AlterModelOptions(
            name='compatability',
            options={'managed': True, 'verbose_name': 'Compatibility', 'verbose_name_plural': 'Compatibilities'},
        ),
        migrations.AlterModelTable(
            name='advantage',
            table='',
        ),
        migrations.AlterModelTable(
            name='batterymodel',
            table='',
        ),
        migrations.AlterModelTable(
            name='compatability',
            table='',
        ),
    ]
