# Generated by Django 3.1.4 on 2020-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201203_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterymodel',
            name='BH_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
