# Generated by Django 3.1.3 on 2020-12-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_advantagesamaron_amaronmodels_amaronseries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compatabilitybike',
            old_name='cs30',
            new_name='C10',
        ),
        migrations.AddField(
            model_name='compatabilitybike',
            name='bike_scooter',
            field=models.CharField(blank=True, choices=[('BK', 'Bike'), ('SC', 'Scooter')], max_length=2),
        ),
        migrations.AddField(
            model_name='compatabilitybike',
            name='capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
