# Generated by Django 3.1.3 on 2020-12-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201203_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatability',
            name='vehicle_class_name',
        ),
        migrations.AddField(
            model_name='compatability',
            name='vehicle_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.application'),
        ),
    ]
