# Generated by Django 3.1.3 on 2020-12-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201202_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batteryrange',
            old_name='mainteence',
            new_name='maintenance',
        ),
    ]
