# Generated by Django 3.1.3 on 2020-12-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201202_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterymodel',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
