# Generated by Django 3.1.3 on 2020-12-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201208_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatabilitybike',
            name='capacity',
        ),
    ]
