# Generated by Django 3.1.3 on 2020-12-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_batterymodel_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batteryrange',
            name='application',
        ),
        migrations.AlterField(
            model_name='advantage',
            name='range_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.batteryrange'),
        ),
        migrations.AlterField(
            model_name='batterymodel',
            name='range_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.batteryrange'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('is_3_wheeler', models.BooleanField(default=False)),
                ('is_small_car', models.BooleanField(default=False)),
                ('is_large_car', models.BooleanField(default=False)),
                ('is_xtra_small_car', models.BooleanField(default=False)),
                ('is_small_van', models.BooleanField(default=False)),
                ('is_truck', models.BooleanField(default=False)),
                ('is_bus', models.BooleanField(default=False)),
                ('is_tractor', models.BooleanField(default=False)),
                ('is_JCB', models.BooleanField(default=False)),
                ('is_construction_vehicle', models.BooleanField(default=False)),
                ('is_bike', models.BooleanField(default=False)),
                ('is_scooter', models.BooleanField(default=False)),
                ('range_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.batteryrange')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
