# Generated by Django 3.1.3 on 2020-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_compatabilitybike_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amaronseries',
            name='price',
        ),
        migrations.AddField(
            model_name='amaronseries',
            name='price_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='batterymodel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bikes',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
