# Generated by Django 3.1.3 on 2020-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201208_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterymodel',
            name='BH_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
