# Generated by Django 3.1.3 on 2020-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201208_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterymodel',
            name='warranty',
            field=models.CharField(max_length=20),
        ),
    ]
