# Generated by Django 3.1.3 on 2020-12-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201208_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amaronmodels',
            name='dealer',
        ),
    ]
