# Generated by Django 3.1.3 on 2020-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_amaronmodels_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaronseries',
            name='series_pic',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
